import Head from 'next/head'
import Link from 'next/link'
import { signIn } from "next-auth/react"
import Layout from '@/components/Layouts/Layout'
import Recommended from '@/components/Home/Recommended'
import Brands from '@/components/Home/Brands'

type Props = {}
export default function Home(props: Props) {

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/github.png" />
      </Head>
      <Layout tittle={'Digital Dreams'}>
        <div className='w-full min-h-[90vh] flex flex-col hide-scrollbar'>
          <Recommended />
          <Brands />
        </div>
      </Layout>
    </>
  )
}
